[package]
name = "universe-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
bevy_egui = "0.20.3"
log = "0.4.17"
rand = "0.8.5"
rand_chacha = "0.3.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
